(()=>{
  const base=new URL('./',location.href);
  const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]||m));
  const resolveHref=v=>{const x=String(v||'#').trim();if(!x)return'#';if(/^(https?:|mailto:|tel:|#)/i.test(x))return x;try{return new URL(x,base).href}catch{return'#'}};
  const defaults={site:{title:'Untoz',description:'Untoz — media, entertainment and technology.',language:'en',theme:'system'},brand:{primary:'#1f6ffa',secondary:'#0cdb46',accent:'#ff7c04'},navigation:{main:[]},header:{show_search:true,show_live:true,live_label:'LIVE',live_href:'#live'},footer:{tagline:'The media, entertainment and technology universe of infinite.',copyright:'© 2026 Untoz. All rights reserved.',links:[]},social:{x:'',youtube:'',instagram:''}};
  function normalize(raw){const r=raw&&typeof raw==='object'?raw:{};return {site:{...defaults.site,...(r.site||{})},brand:{...defaults.brand,...(r.brand||{})},navigation:{main:Array.isArray(r.navigation?.main)?r.navigation.main:[]},header:{...defaults.header,...(r.header||{})},footer:{...defaults.footer,...(r.footer||{}),links:Array.isArray(r.footer?.links)?r.footer.links:[]},social:{...defaults.social,...(r.social||{})}}}
  function injectTheme(c){document.documentElement.style.setProperty('--untoz-primary',c.brand.primary);document.documentElement.style.setProperty('--untoz-secondary',c.brand.secondary);document.documentElement.style.setProperty('--untoz-accent',c.brand.accent);let s=document.getElementById('untoz-live-shell-style');if(!s){s=document.createElement('style');s.id='untoz-live-shell-style';document.head.appendChild(s)}s.textContent=`.untoz-site-header__logo:after{background:var(--untoz-secondary)!important}.pill.primary,.filters button.active{background:var(--untoz-primary)!important;border-color:var(--untoz-primary)!important;color:#fff!important}.section-title a,.stories-head>a,.live-strip>a{color:var(--untoz-primary)!important}`}
  function applyMeta(c){document.documentElement.lang=c.site.language||'en';document.title=`${c.site.title||'Untoz'} — The Untoz Media Portal`;const d=document.querySelector('meta[name="description"]');if(d)d.content=c.site.description||defaults.site.description;const og=document.querySelector('meta[property="og:title"]');if(og)og.content=document.title;const ogd=document.querySelector('meta[property="og:description"]');if(ogd)ogd.content=c.site.description||defaults.site.description;const tw=document.querySelector('meta[name="twitter:title"]');if(tw)tw.content=document.title;const twd=document.querySelector('meta[name="twitter:description"]');if(twd)twd.content=c.site.description||defaults.site.description;document.querySelector('meta[name="theme-color"]')?.setAttribute('content',c.site.theme==='dark'?'#0f1116':'#ffffff');if(c.site.theme==='dark'||c.site.theme==='light'){document.documentElement.dataset.theme=c.site.theme;localStorage.setItem('untoz-theme',c.site.theme)}}
  function applyHeader(c){const desktop=document.querySelector('.untoz-site-header__nav'),mobile=document.querySelector('.untoz-site-header__mobile-nav');const items=c.navigation.main.filter(x=>x&&x.label);const markup=items.map((x,i)=>`<a class="${i===0?'active':''}" href="${esc(resolveHref(x.href))}">${esc(x.label)}</a>`).join('');if(desktop&&items.length)desktop.innerHTML=markup;if(mobile&&items.length){mobile.innerHTML=markup;mobile.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{mobile.classList.remove('open');const t=document.getElementById('siteMenuToggle');if(t)t.textContent='☰'}))}const search=document.querySelector('.untoz-site-header__action.desktop-only');if(search){search.hidden=!c.header.show_search;search.href=resolveHref('search/')}const live=document.querySelector('.untoz-site-header__live');if(live){live.hidden=!c.header.show_live;live.href=resolveHref(c.header.live_href);live.innerHTML=`<i></i> ${esc(c.header.live_label||'LIVE')}`}const logo=document.querySelector('.untoz-site-header__logo');if(logo)logo.textContent=String(c.site.title||'Untoz').toLowerCase()}
  function applyFooter(c){const footer=document.getElementById('footer');if(!footer)return;const brand=footer.querySelector('.footer-inner>div:first-child .brand');if(brand)brand.textContent=String(c.site.title||'Untoz').toLowerCase();const tagline=footer.querySelector('.footer-inner>div:first-child p');if(tagline)tagline.textContent=c.footer.tagline||'';const bottom=footer.querySelector('.footer-bottom');if(bottom){const links=bottom.querySelector('div');if(links)links.innerHTML=(c.footer.links||[]).map(x=>`<a href="${esc(resolveHref(x.href))}">${esc(x.label)}</a>`).join('');const copy=bottom.querySelector('span');if(copy)copy.textContent=c.footer.copyright||''}const social=footer.querySelector('.social');if(social){const values=[[c.social.x,'X'],[c.social.youtube,'▶'],[c.social.instagram,'◎']];social.innerHTML=values.filter(([url])=>url).map(([url,label])=>`<a href="${esc(resolveHref(url))}" target="_blank" rel="noopener noreferrer">${label}</a>`).join('');social.hidden=!values.some(([url])=>url)}}
  function applyBrands(data){const brands=Array.isArray(data?.brands)?data.brands.filter(b=>b&&b.enabled!==false):[];const cards=[...document.querySelectorAll('.explore-card')];if(!brands.length||!cards.length)return;brands.slice(0,cards.length).forEach((b,i)=>{const card=cards[i];card.href=resolveHref(`${b.id}/`);card.dataset.brand=b.id||'';card.style.borderColor=b.accent||'';const label=card.querySelector('span');if(label)label.textContent=b.name||b.short||b.id;const icon=card.querySelector('div');if(icon)icon.textContent=['◆','⚽','⌘','◌','☆','✦','▣'][i%7]});cards.forEach((c,i)=>{if(i>=brands.length)c.hidden=true})}
  function apply(siteData,brandData){const c=normalize(siteData);injectTheme(c);applyMeta(c);applyHeader(c);applyFooter(c);applyBrands(brandData);window.dispatchEvent(new CustomEvent('untoz:site-shell-applied',{detail:{config:c}}))}
  Promise.all([
    fetch(new URL('content/site.json',base),{cache:'no-store'}).then(r=>r.ok?r.json():{}).catch(()=>({})),
    fetch(new URL('content/brands.json',base),{cache:'no-store'}).then(r=>r.ok?r.json():{}).catch(()=>({}))
  ]).then(([siteData,brandData])=>apply(siteData,brandData));
})();
