import React, { useEffect, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { ArrowRight, ArrowUpRight, Menu, Radio, Film, Newspaper, Sparkles, MonitorPlay, X, Sun, Moon, Search, Globe2, Users, Eye, CalendarDays } from 'lucide-react'
import './styles.css'
import './theme.css'

const capabilities=[['Live Broadcasting','We broadcast your event to the world with professional quality.',Radio],['Video Production','From concept to final cut. We create stunning videos that tell your story.',Film],['Streaming Solutions','Multi-platform streaming, 24/7 channels and custom solutions.',MonitorPlay],['News Coverage','Fast, accurate and reliable news from everywhere.',Newspaper],['Sports Media','Live sports, highlights, analysis and exclusive content.',Globe2],['AI Solutions','Innovative AI tools and solutions for the future of media.',Sparkles]]
const products=[['untoz+','plus','The streaming platform of the future.'],['untoz studio ai','studio','AI-powered tools for creators and storytellers.'],['untoz hq','hq','Manage your AI workforce and projects.'],['untoz motion ai','motion','Create stunning motion designs with AI.'],['untoz one','one','All-in-one AI tools for everyone.']]
const projects=[['New Year 2026 Celebrations','Live Broadcast','https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=1000&q=80'],['Starship Flight Test Coverage','Live Broadcast','https://images.unsplash.com/photo-1517976547714-720226b864c1?auto=format&fit=crop&w=1000&q=80'],['Untoz Awards 2026 Dubai','Live Event','https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=1000&q=80'],['Artemis II: Return to the Moon','Documentary','https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?auto=format&fit=crop&w=1000&q=80'],['Untoz Fest 2026 Highlights','Event Coverage','https://images.unsplash.com/photo-1501386761578-eac5c94b800a?auto=format&fit=crop&w=1000&q=80']]
const news=[['11/07/2026','Untoz Announces Official Untoz+ Launch Event for August 12','COMPANY'],['28/06/2026','Update on Untoz+','PRODUCTS'],['01/07/2026','Untoz Fest 2026 will take place from August 12 to 13','EVENTS'],['05/07/2026',"Untoz Marks America's 250th Anniversary with a 7-Hour Live",'LIVE']]
function GlobalHeader(){return <div className="global-header"><a className="global-brand" href="#top">UNTOZ</a><nav className="global-nav"><a href="#products">UNTOZ+</a><a href="#news">NEWS</a><a href="#projects">SPORTS</a><a href="#products">GAMING</a><button className="global-more">MORE +</button></nav><button className="global-menu"><Menu size={17}/></button></div>}
function SiteHeader({dark,setDark}){const[open,setOpen]=useState(false);return <header className="site-header"><a className="site-logo" href="#top">untoz</a><nav className="site-nav"><a href="#top">Home</a><a href="#products">Products</a><a href="#about">Services</a><a href="#projects">Projects</a><a href="#news">News</a><a href="#about">About</a><a href="#contact">Contact</a></nav><div className="header-actions"><button className="icon-button" aria-label="Search"><Search size={15}/></button><button className="theme-toggle" aria-label="Toggle theme" onClick={()=>setDark(!dark)}>{dark?<Sun size={15}/>:<Moon size={15}/>}</button><a className="watch-button" href="#projects">Watch Live <Radio size={12}/></a><button className="mobile-menu-button" onClick={()=>setOpen(!open)}>{open?<X size={18}/>:<Menu size={18}/>}</button></div>{open&&<nav className="mobile-nav">{['Home','Products','Services','Projects','News','About','Contact'].map(x=><a key={x} href={x==='Home'?'#top':x==='Products'?'#products':x==='Projects'?'#projects':x==='News'?'#news':x==='Contact'?'#contact':'#about'} onClick={()=>setOpen(false)}>{x}</a>)}</nav>}</header>}
function App(){const[scroll,setScroll]=useState(0);const[dark,setDark]=useState(true);useEffect(()=>{const f=()=>setScroll(window.scrollY);addEventListener('scroll',f);return()=>removeEventListener('scroll',f)},[]);useEffect(()=>{document.documentElement.dataset.theme=dark?'dark':'light'},[dark]);return <div id="top" className="app"><GlobalHeader/><SiteHeader dark={dark} setDark={setDark}/><div className="scroll-progress" style={{transform:`scaleX(${Math.min(scroll/(document.documentElement.scrollHeight-window.innerHeight||1),1)})`}}/><main>
<section className="hero section-pad"><div className="hero-copy"><p className="eyebrow">UNTOZ MEDIA GROUP</p><h1>Creating the<br/>future of<br/><em>entertainment.</em></h1><p className="hero-description">We produce, create and deliver world-class content, live events and digital experiences to audiences around the world.</p><div className="hero-actions"><a className="primary-button" href="#projects">Explore Our Work <ArrowRight size={15}/></a><a className="secondary-button" href="#about">Our Services</a></div></div><div className="hero-art"><div className="hero-image"/><div className="stage-lights"/><div className="hero-screen">untoz<span>+</span></div><div className="hero-crowd"/><div className="hero-live"><span>● LIVE NOW</span><strong>New Year 2026 Celebrations</strong><small>Watch on Untoz+</small></div><div className="hero-dots"><i/><i/><i/></div></div></section>
<section id="about" className="about section-pad"><div className="section-kicker">WHAT WE DO</div><h2 className="center-heading">Everything we do. <span>For everyone.</span></h2><div className="capability-grid">{capabilities.map(([title,text,Icon])=><article className="capability-card" key={title}><div className="capability-icon"><Icon size={21}/></div><div><h3>{title}</h3><p>{text}</p><a href="#contact">Learn more <ArrowRight size={12}/></a></div></article>)}</div></section>
<section id="products" className="products section-pad"><div className="section-heading"><div><div className="section-kicker">OUR PRODUCTS</div><h2>Built for <span>the future.</span></h2></div><a className="text-link" href="#products">See all products <ArrowRight size={13}/></a></div><div className="product-strip">{products.map(([name,accent,description])=><article className={`product-card ${accent}`} key={name}><div className="product-logo">{name}</div><div className="product-info"><h3>{name}</h3><p>{description}</p></div></article>)}<button className="strip-next"><ArrowRight size={14}/></button></div></section>
<section id="projects" className="projects section-pad"><div className="section-heading"><div><div className="section-kicker">FEATURED PROJECTS</div><h2>Our latest <span>projects.</span></h2></div><a className="text-link" href="#projects">View all projects <ArrowRight size={13}/></a></div><div className="project-grid">{projects.map(([title,type,image])=><article className="project-card" key={title}><div className="project-image" style={{backgroundImage:`url(${image})`}}/><div className="project-overlay"/><div className="project-copy"><h3>{title}</h3><p>{type}</p></div></article>)}</div></section>
<section className="numbers section-pad"><div className="stats"><div><Users/><strong>100<span>+</span></strong><p>Productions</p></div><div><Radio/><strong>50<span>+</span></strong><p>Live Broadcasts</p></div><div><Eye/><strong>10M<span>+</span></strong><p>Views Worldwide</p></div><div><Globe2/><strong>150<span>+</span></strong><p>Countries Reached</p></div><div><CalendarDays/><strong>Since 2020</strong><p>Creating Experiences</p></div></div></section>
<section id="news" className="news section-pad"><div className="section-heading"><div><div className="section-kicker">LATEST NEWS</div><h2>Stay up to <span>date.</span></h2></div><a className="text-link" href="#news">View all news <ArrowRight size={13}/></a></div><div className="news-grid">{news.map(([date,title,category])=><article key={title}><div className="news-thumb"><span>{category==='COMPANY'?'untoz':category==='PRODUCTS'?'untoz+':category==='EVENTS'?'FEST 26':'✦'}</span></div><div className="news-body"><small>{date}</small><h3>{title}</h3><a href="#news">Read more <ArrowRight size={12}/></a></div></article>)}</div></section>
<section id="contact" className="broadcast-cta"><div><h2>Have an event to broadcast?</h2><p>We'll help you reach the world.</p><a className="primary-button" href="#contact">Request a Broadcast <ArrowRight size={14}/></a></div><div className="cta-features"><span><Sparkles/>Professional<br/>Production</span><span><Globe2/>Worldwide<br/>Streaming</span><span><MonitorPlay/>Multi-Platform<br/>Delivery</span><span><Users/>End-to-End<br/>Support</span></div></section></main><footer className="footer section-pad"><div className="footer-bottom"><span>© 2026 Untoz Media Group. All rights reserved.</span><div><a href="#top">X</a><a href="#top">YouTube</a><a href="#top">Instagram</a><a href="#top">TikTok</a><a href="#top">Facebook</a></div></div></footer></div>}
createRoot(document.getElementById('root')).render(<React.StrictMode><App/></React.StrictMode>)
